cmake_minimum_required(VERSION 3.10)
project(arraylib)

set(CMAKE_CXX_STANDARD 17)

add_library(arraylib SHARED arraylib.cpp)
target_include_directories(arraylib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
add_executable(app main.cpp)
target_link_libraries(app PRIVATE arraylib)
enable_testing()
add_executable(test_arraylib tests/test_arraylib.cpp)
target_link_libraries(test_arraylib PRIVATE arraylib)
add_test(NAME ArrayTests COMMAND test_arraylib)
add_executable(variant_03 examples/variant_03.cpp)
target_link_libraries(variant_03 PRIVATE arraylib)
add_executable(test_integration tests/test_integration.cpp)
target_link_libraries(test_integration PRIVATE arraylib)
add_test(NAME IntegrationTests COMMAND test_integration)